name: Bundle Size Analysis Example

on:
  pull_request:
  push:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build Next.js application
        run: npm run build
      
      - name: Analyze bundle sizes
        uses: SinaTZ0/next-bundle-size-action@master
        with:
          working-directory: '.'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-strategy: 'always'
          base-branch: 'main'
